[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 5
[[main]]
  identifier = "homeopathy"
  name = "Homeopathy"
  url = "/homeopathy/"
  weight = 10
[[main]]
  identifier = "biography"
  name = "Biography"
  url = "/biography/"
  weight = 20
[[main]]
  identifier = "FAQ"
  name = "FAQ"
  url = "/faq/"
  weight = 30
[[main]]
  identifier = "pricing"
  name = "Pricing"
  url = "/pricing/"
  weight = 40
[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 50
